name: CI

on:
  push:
    paths:
      - 'src/**'
    branches:
    - master
  pull_request:
    paths:
      - 'src/**'
    branches:
    - master

jobs:
  test:
    name: Node.js v${{ matrix.nodejs }}
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        nodejs: [8, 10, 12, 14]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodejs }}

    - name: (env) pnpm
      run: curl -L https://raw.githubusercontent.com/pnpm/self-installer/master/install.js | node

    - name: (env) cache
      uses: actions/cache@master
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}

    - name: Install
      run: |
        pnpm install
        pnpm install -g nyc@13

    - name: Compiles
      run: pnpm run build

    - name: Test w/ Coverage
      run: nyc --include=src pnpm test

    - name: Report
      if: matrix.nodejs >= 14
      run: |
        nyc report --reporter=text-lcov > coverage.lcov
        bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
